const modulePaths = [
  { label: "Accordion", path: "/accordion" },
  { label: "Auto Complete", path: "/autoComplete" },
  { label: "Carousel", path: "/carousel" },
  { label: "Countdown Timer", path: "/countdownTimer" },
  { label: "CSS Grid", path: "/cssGrid" },
  { label: "Debouncing", path: "/debouncing" },
  { label: "Display Time", path: "/displayTime" },
  { label: "Dropdown", path: "/dropdown" },
  { label: "Dropdown 2", path: "/dropdown2" },
  { label: "Dynamic Tabs", path: "/dynamicTabs" },
  { label: "GitHub Profile Finder", path: "/gitHubProfileFinder" },
  { label: "Infinite Scrolling", path: "/infiniteScrolling" },
  { label: "Modal", path: "/modal" },
  { label: "Navigation Menu", path: "/navigationMenu" },
  { label: "QR Code Generator", path: "/qrCodeGenerator" },
  { label: "Random Color Generator", path: "/randomColorGenerator" },
  { label: "Scroll Indicator", path: "/scrollIndicator" },
  { label: "Stacked Cards", path: "/stackedCards" },
  { label: "Star Rating", path: "/starRating" },
  { label: "Theme Changer", path: "/themeChanger" },
  { label: "Throttling", path: "/throttling" },
  { label: "Tic Tac Toe", path: "/ticTacToe" },
  { label: "Todo", path: "/todo" },
];

export default modulePaths;
